version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running migrations...
      - python manage.py migrate
  post_build:
    commands:
      - echo Build completed successfully!
      # You may add additional commands for deployment here if necessary

artifacts:
  files:
    - '**/*'
  base-directory: project1
