version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Install system dependencies
      - dnf install -y python3-devel python3-pip
      - dnf install -y postgresql-devel
      # Install Python dependencies
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt

  build:
    commands:
      # Run tests
      - python3 manage.py test

  post_build:
    commands:
      # Apply database migrations
      - python3 manage.py makemigrations
      - python3 manage.py migrate
      # Package the application (e.g., Docker, zip, etc.)
      # This step depends on the deployment method you choose

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'build'