version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Update system packages
      - apt-get update
      # Install system dependencies
      - apt-get install -y python3-dev python3-pip
      # Install Python dependencies
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt

  build:
    commands:
      # Run tests
      - python3 manage.py test

  post_build:
    commands:
      # Apply database migrations
      - python3 manage.py makemigrations
      - python3 manage.py migrate
