version: 0.2

env:
  variables:
    PROJECT_DIR: "/home/ubuntu/Django-Training/"
    REQUIREMENTS_FILE: "/home/ubuntu/Django-Training/requirements.txt"
    VIRTUAL_ENV: "venv"

phases:
  pre_build:
    commands:
      - echo "Installing Python dependencies"
      - apt-get update
      - apt-get install -y python3-pip python3-venv
      - python3 -m venv ${VIRTUAL_ENV}

  build:
    commands:
      - echo "Virtual Environment starts"
      - source venv/bin/activate
      - pip3 install -r ${REQUIREMENTS_FILE} 
      - echo "Running Django database migrations!"
      - python ${PROJECT_DIR}manage.py makemigrations
      - python ${PROJECT_DIR}manage.py migrate

artifacts:
  files:
    - '**/*'
