version: 0.1

env:
  variables:
    PROJECT_DIR: "/home/ubuntu/Django-Training/"
    REQUIREMENTS_FILE: "/home/ubuntu/Django-Training/requirements.txt"
    VIRTUAL_ENV: "venv"

phases:
  pre_build:
    commands:
      - echo "Installing AWS CLI"
      - apt-get update
      - apt-get install -y awscli
      - cd ${PROJECT_DIR}
      - source ${VIRTUAL_ENV}/bin/activate
      - pip3 install -r ${REQUIREMENTS_FILE}
  build:
    commands:
      - echo "No build commands specified for Django project"
      - python ${PROJECT_DIR}manage.py makemigrations
      - python ${PROJECT_DIR}manage.py migrate

artifacts:
  files:
    - '**/*'

deploy:
  provider: CodeDeploy
  deployment_group: "deployment group you created"
  region: ap-south-1
  wait-until-deployed: true