version: '3'

services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: db_name
  #     POSTGRES_USER: db_user
  #     POSTGRES_PASSWORD: db_password
  #   ports:
  #     - "5432:5432"

  web:
    # image: aakarshak1/django_project
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
