# Generated by Django 3.2.24 on 2024-03-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='teacher',
        ),
    ]
