# Generated by Django 3.2.24 on 2024-03-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240313_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='teacher',
        ),
    ]
