# Generated by Django 3.2.24 on 2024-03-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_user_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
